In [9]:
import numpy as np
import matplotlib as plt
e = np.exp(1)
pi = np.pi 
i = 1j

print (e**((i*pi)/2))

(6.123233995736766e-17+1j)


Aufgabe a

In [2]:
print(1*2**3+4)

12


Aufgabe b

In [3]:
pi = np.pi
var1 = e**(i*pi/2)
print(var1)

(6.123233995736766e-17+1j)


Eigentlich dürfte nur derImaginärteil als ergebnis rauskommen, da vom reellen 90° (π/2) nur Imaginärteil übrig bleiben müsste
Der Realteil "6.123233995736766e-17" ist ein rundungsfehler.

Aufgabe d

In [4]:
z = 1+ 2j
print(z)

(1+2j)


In [8]:

matrix1 = np.matrix(([1],[2],[3]))
print("numpy matrix:")
print(matrix1)

ones1= np.ones(3)
print("numpy ones mit 3:")
print(ones1)

matrix2 = matrix1 * ones1
print("Matrix2:")
print(matrix2)


numpy matrix:
[[1]
 [2]
 [3]]
numpy ones mit 3:
[1. 1. 1.]
Matrix2:
[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]
