In [3]:
#Faltungsrechner
import numpy as np
def lineareFaltungRechner(a,b):
    faltung = np.convolve(np.flipud(a),b)
    print("Faltungsergebnis:", np.flipud(a),"*",b,"=",faltung)

    #Rechnungsdarstellung als Matrix
    l = a.size + b.size -1 #länge des erbegnisarrays
    a = np.append(a, np.zeros(l-a.size))
    b = np.insert(b, 0, np.zeros(l-b.size))
    print("")
    print("Rechnungsdarstellung: a * b")
    for i in range(l):
        if (i == 0):
            temp = "  ="
            for g in range(len(a)):
                if (a[g] == 0 or b[g] == 0):
                    pass
                else:
                    if (temp == "  ="):
                        str1 = a[g],"*",b[g]
                        temp = " = "+str(str1)
                    else:
                        str1 = a[g],"*",b[g]
                        temp = temp+"+"+str(str1)
            print(a, " [",b[i],"] = [",faltung[i],"]", temp)
            #print(temp)
        else:
            a = np.insert(a, 0, np.zeros(1))
            a = a[:-1]
            temp = "  ="
            for g in range(len(a)):
                if (a[g] == 0 or b[g] == 0):
                    pass
                else:
                    if (temp == "  ="):
                        str1 = a[g],"*",b[g]
                        temp = " = "+str(str1)
                    else:
                        str1 = a[g],"*",b[g]
                        temp = temp+"+"+str(str1)
            
            print(a, " [",b[i],"] = [",faltung[i],"]", temp)

# Beispiel

In [7]:
x_1 = np.array([3,2,1])
x_2 = np.array([3,3,3,3])
lineareFaltungRechner(x_1,x_2)

Faltungsergebnis: [1 2 3] * [3 3 3 3] = [ 3  9 18 18 15  9]

Rechnungsdarstellung: a * b
[3. 2. 1. 0. 0. 0.]  [ 0 ] = [ 3 ]  = (1.0, '*', 3)
[0. 3. 2. 1. 0. 0.]  [ 0 ] = [ 9 ]  = (2.0, '*', 3)+(1.0, '*', 3)
[0. 0. 3. 2. 1. 0.]  [ 3 ] = [ 18 ]  = (3.0, '*', 3)+(2.0, '*', 3)+(1.0, '*', 3)
[0. 0. 0. 3. 2. 1.]  [ 3 ] = [ 18 ]  = (3.0, '*', 3)+(2.0, '*', 3)+(1.0, '*', 3)
[0. 0. 0. 0. 3. 2.]  [ 3 ] = [ 15 ]  = (3.0, '*', 3)+(2.0, '*', 3)
[0. 0. 0. 0. 0. 3.]  [ 3 ] = [ 9 ]  = (3.0, '*', 3)
