# 1. Erstellen von Arrays:

Erstelle ein 1D-Array mit den Werten [1, 2, 3, 4, 5].

## Erstelle ein 2D-Array mit den Werten [[1, 2], [3, 4], [5, 6]].

In [20]:
import numpy as np
print([1,2,3,4])
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)


[1, 2, 3, 4]
[[1 2 3 4]
 [5 6 7 8]]

np.zeros
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Erstelle ein 3x3-Array mit Nullen mit "np.zeros".

In [24]:
print(np.zeros((3, 3)))


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Erstelle ein 4x2-Array mit Einsen mit "np.ones"

In [33]:
np.arange(1,16).reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])