<h1>Faltung</h1>

In [5]:
import numpy as np

Brechnet das Faltungsergebnis von [9,8,1] und [3,5,6,9]. Erstellt dazu ambesten einen Rechner der den Lösungsweg mit ausgibt.

In [6]:
def faltungklein(a,b):

    print("Faltungsergebnis:",np.convolve(np.flipud(a),b))
    l = a.size + b.size -1 #länge des erbegnisarrays
    c = np.arange(l)
    helper = np.arange(0,a.size)
    la = a.size -1
    a = np.append(a, np.zeros(l-a.size))
    b = np.insert(b, 0, np.zeros(l-b.size))
    print("Länge des Faltungsergebnis:",l)
    print("Array a:",a,"(Fliped)")
    print("Array b:",b.reshape(l,1))
    for i in range(l):
        print(np.roll(a, i-l)[la:])

a = np.flipud(np.array([9,8,1]))
b = np.array([3,5,6,9])

faltungklein(a,b)

Faltungsergebnis: [ 27  69  97 134  78   9]
Länge des Faltungsergebnis: 6
Array a: [1. 8. 9. 0. 0. 0.] (Fliped)
Array b: [[0]
 [0]
 [3]
 [5]
 [6]
 [9]]
[9. 0. 0. 0.]
[8. 9. 0. 0.]
[1. 8. 9. 0.]
[0. 1. 8. 9.]
[0. 0. 1. 8.]
[0. 0. 0. 1.]


Gefaltet werden die Folgen [5,2,8,9,4,2,6,8] und [2,6,8,9,0,4,2,5,6,9,6] Wie lang ist die Ausgangsfolge?

In [7]:
a = np.flipud(np.array([5,2,8,9,4,2,6,8]))
b = np.array([2,6,8,9,0,4,2,5,6,9,6])

faltungklein(a,b)

Faltungsergebnis: [ 10  34  68 127 144 192 155 165 206 249 229 186 207 148 118 114 108  48]
Länge des Faltungsergebnis: 18
Array a: [8. 6. 2. 4. 9. 8. 2. 5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] (Fliped)
Array b: [[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [2]
 [6]
 [8]
 [9]
 [0]
 [4]
 [2]
 [5]
 [6]
 [9]
 [6]]
[5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[2. 5. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[8. 2. 5. 0. 0. 0. 0. 0. 0. 0. 0.]
[9. 8. 2. 5. 0. 0. 0. 0. 0. 0. 0.]
[4. 9. 8. 2. 5. 0. 0. 0. 0. 0. 0.]
[2. 4. 9. 8. 2. 5. 0. 0. 0. 0. 0.]
[6. 2. 4. 9. 8. 2. 5. 0. 0. 0. 0.]
[8. 6. 2. 4. 9. 8. 2. 5. 0. 0. 0.]
[0. 8. 6. 2. 4. 9. 8. 2. 5. 0. 0.]
[0. 0. 8. 6. 2. 4. 9. 8. 2. 5. 0.]
[0. 0. 0. 8. 6. 2. 4. 9. 8. 2. 5.]
[0. 0. 0. 0. 8. 6. 2. 4. 9. 8. 2.]
[0. 0. 0. 0. 0. 8. 6. 2. 4. 9. 8.]
[0. 0. 0. 0. 0. 0. 8. 6. 2. 4. 9.]
[0. 0. 0. 0. 0. 0. 0. 8. 6. 2. 4.]
[0. 0. 0. 0. 0. 0. 0. 0. 8. 6. 2.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 8. 6.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 8.]


Ein lineares, zeitinvariantes System wird mit der Folge [4,3,3,10,9,6] angeregt und antwortet mit [4,13,20,27,30,40,36,27,20,13,10].

Wie lang ist die Stoßantwort des Systems?

In [8]:
def linearConvolution(fa,Aa,w):
    arr = np.zeros(Aa.size+fa.size*(w-1))
    for i in range(w):
        temp = np.insert(Aa, 0, np.zeros(fa.size*i))
        temp2 = np.append(temp,np.zeros(fa.size*((w-1)-i)))
        #print(temp2)
        
        arr = arr+temp2
    print("stossantwort:",Aa.size+1-fa.size)
    print("Ergebnis Array:",arr)

#angeregte Folge
fa = np.array([4,3,3,10,9,6])
#antwort
Aa = np.array([ 4,13,20,27,30,40,36,27,20,13,10])
#anzahl der wiederholungen
w = 2

linearConvolution(fa,Aa,w)

stossantwort: 6
Ergebnis Array: [ 4. 13. 20. 27. 30. 40. 40. 40. 40. 40. 40. 40. 36. 27. 20. 13. 10.]


Berechnet das Ergebnis,wenn dieses System zweimal unmittelbar hintereinander mit der gegebenen Anregungsfolge angeregt wird!

In [9]:
#angeregte Folge
fa = np.array([4,3,3,10,9,6])
#antwort
Aa = np.array([ 4,13,20,27,30,40,36,27,20,13,10])
#anzahl der wiederholungen
w = 2

linearConvolution(fa,Aa,w)

stossantwort: 6
Ergebnis Array: [ 4. 13. 20. 27. 30. 40. 40. 40. 40. 40. 40. 40. 36. 27. 20. 13. 10.]
